# Generated by Django 4.0.3 on 2022-05-06 16:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('disque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disquaire',
            name='num_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
