# Generated by Django 4.0.3 on 2022-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disque', '0002_alter_disquaire_num_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disque',
            name='date_sortie',
            field=models.DateField(blank=True, null=True, verbose_name='% d/% m/% Y'),
        ),
        migrations.AlterField(
            model_name='disque',
            name='duree',
            field=models.IntegerField(blank=True, verbose_name='% [0-9]:[0-9]'),
        ),
    ]
