# Generated by Django 4.0.3 on 2022-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disque', '0003_alter_disque_date_sortie_alter_disque_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disque',
            name='duree',
            field=models.DurationField(),
        ),
    ]
