# Generated by Django 4.0.3 on 2022-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disque', '0004_alter_disque_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disque',
            name='date_sortie',
            field=models.DateField(blank=True, null=True, verbose_name='([1-9]|([012][0-9])|(3[01]))-([0]{0,1}[1-9]|1[012])'),
        ),
    ]
