# Generated by Django 4.0.3 on 2022-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disque', '0006_alter_disquaire_num_tel_alter_disque_date_sortie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disque',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
