# Generated by Django 4.0.3 on 2022-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disque', '0007_disque_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disquaire',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
