# Generated by Django 4.0.3 on 2022-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disque', '0010_alter_disque_duree_alter_disque_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disque',
            name='genre',
            field=models.CharField(choices=[('Non précisé', 'Non précisé'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Techno', 'Techno'), ('Electro', 'Electro'), ('Indie rock', 'Indie rock'), ('Pop', 'Pop'), ('Métal', 'Métal'), ('Classique', 'Classique')], default='NON_PRECISE', max_length=15, verbose_name='Genre'),
        ),
    ]
